### PR TITLE
Translation memory for nb-NO and Python improvements+fixes

### PR DESCRIPTION
**Pull request by benediktkr**

### CODE REVIEW

**Comment by benediktkr** [comment]
The merged `.csv` file of the translation memory was generated from the files extracted from `nb_translation_ui_strings_glossaries_september_2020_x86_x64_f09fcf3c.zip`, that was downloaded from [Visual Studio Dev Essentials](https://my.visualstudio.com/downloads?pid=6822) as "Translation and UI Strings Glossaries September 2020". 

I have also downloaded the Glossary file `MicrosoftTermCollection.tbx` from the [Download Terminology](https://www.microsoft.com/en-us/language/Terminology) page at microsoft.com (I [have several versions](https://static.sudo.is/microsoft-terminology/) from 2021, 2022 and 2023). 

I have converted the `nb-NO` files from `.tbx` to `.sdltb`, but I'm not quite sure how to convert them to `.csv` files (the `README.md` on the Spidersouris/termic repo suggests using XBench to convert it to `.xlsx`, but that isnt `.csv` (i know that `.xls` are basically "fancy csv files", but i dont know if thats also true for xlsx files). Can i just feed `.xlsx` files to panda's `read_csv` function, or am I missing something?

**Comment by spidersouris** [comment]
Hey! Thank you very much for the PR and sorry for the delay.

The way termic is set up currently is that there are two different tables for each language (one for TM [CSV files] and one for glossary [XLSX files]). CSV files are merged into one single file using pandas, but XLSX files can be integrated directly to a table without any issues (at least, using Microsoft ADF). These files do not require specific treatment.

Reg. data files for Norwegian, I do not think they should be added to the project. Originally, these files were added to the termic-data repo but it's becoming too huge for GitHub. Will probably move everything to Dropbox in a couple of weeks.

Will check the Python improvements before tomorrow :)

**Comment by spidersouris** [comment]
Wow. Was really tired yesterday. Didn't notice this is indeed the termic-data repo! Sorry about that.

Anyway -- just to clarify on what I've posted yesterday: I'm planning on moving all the data from this repo to some Dropbox folder because of GitHub's repo size limit. So I guess we can still add the Norwegian content to this repo, but in the end, my plans are to move all the scripts used for extraction to a specific folder in https://github.com/Spidersouris/termic so that everything is at the same place, and add a link to the Dropbox folder containing all the language files (both for glossary and TM). So this repo will probably get archived in a couple of weeks (but the latest versions of the scripts will be moved to the termic repo before it's archived).

The improvements to the script look good to me -- thank you very much!

**Comment by benediktkr** [comment]
That makes sense to me! And i agree, git isnt meant to store data in this way (check out `git annex` or `git lfs` if you're interested though, but i've never really used either of those). 

If you want to use something other than Dropbox i can also provide you with reliable hosting for this project. Alternatively you could use an S3-compatible service like [Wasabi](https://www.wasabi.com) which is quite cheap. Or if you would prefer to keep it in git without concern for size limitations on repos for the time being for simplicity reasons --- youre also free to use [my Gitea server](https://git.sudo.is/) if that would make anything easier for you. But long term I do think this shouldnt be kept in git, because its not the sort of data that git is designed for. 

Also another better option would be to store the source files (assuming Microsoft's license allows this) in this repo (or the main repo), and merging them on build-time (or writing directly to the database -- thanks for the explanation on how these data files are used). I'll probably end up writing a `Dockerfile` for this, and imo that would fit well as a build-step for the Docker image. I also want to make `termic` into a Python-package, though the usual tools I use for that ([poetry](https://python-poetry.org)) are not flexible enough for that, but using something like `fpm` to create either a `.deb`/`.rpm` package would be able to handle that. 

Regarding the Python improvements, i'm planning on also reworking some thing in your main Termic repo. There are some issues (that I would prefer to not bring up here in the open before theyre fixed) as well as making some thing more Pythonic, and I'll also be setting up and hosting an instance of Termic. 

Thanks for this project btw, it's an awesome initiative!

**Comment by benediktkr** [comment]
ah and about the Glossary files:  

* I have `MicrosoftTermCollection.tbx`  (for `nb-NO`)
* I had previously converted it to a `.sdltb` file (in order to import it into Trados), from the `.tbx` file by converting it with either "SDL MultiTerm" or "Glossary Converter". 

Should I be using XBench to convert it to an `.xlsx` file for `termic` to use? Basically, i need to convert the `.tbx` file I downloaded from Microsoft into an `.xlsx` file?

**Comment by spidersouris** [comment]
I tried `git lfs` but it only works on a file basis (that is, you can upload files bigger than 100MB but you're still limited by the maximum repo size).

Thank you so much for the hosting suggestions as well as your offer :) I have a Dropbox subscription that I'm not fully using so I thought it could be beneficial to use it to store termic data (instead of using/paying for another hosting service). That's most probably the path I'm going to go with.

Merging the source files on build time could indeed be an interesting solution but I think we'd still be limited by GitHub's size restrictions?

I'm extremely glad to hear that you're excited about the project and that you want to contribute more to it. That's really heartwarming! And I'm always up for feedback so please feel free to bring up things that you think should be improved. Just to be fully transparent, development has been halted a bit due to personal stuff going on (hence the delays in replying; sorry!); and also because I'm waiting to see what Microsoft offers with the integration of the MLP to the Microsoft Learn service. So things should be back to normal around the beginning of July on my side.

___

Reg. glossary: the only workflow I've tried so far is indeed converting the Microsoft-provided .tbx files to .xlsx using XBench. XBench-generated files are pretty clean; there are just some redundant columns (starting column 8/9 approximately) with data such as file path/date that we're not interested in. I also add an extra header row at the top just to make it easier to import it with Microsoft Azure (specifying whether the column is term, part of speech, description, etc.). Here's [an example for Czech](https://arxius.io/f/2c97a8ab). This was done manually so far as it really doesn't take very long to do but it wouldn't take much to write a quick Python script to do this automatically (would be much user-friendly that way).

**Comment by benediktkr** [comment]
> Merging the source files on build time could indeed be an interesting solution but I think we'd still be limited by GitHub's size restrictions?

Only if you are using Github :) the build process can pull it down from Dropbox on build-time (if you want to be fancy about it, we could/should sign the downloaded blob with a known/published key). 

I'll write more later when i have more time, and something to show. ive started (got my dev env working) to fix the bugs and work on the releasing/packaging and a `Dockerfile`. 

btw if you use matrix, you can find me as [@ben:sudo.is](https://matrix.to/#/@ben:sudo.is).

**Pull request merged**
